/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/comments` | `/comments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/detail` | `/detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/edit` | `/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/files` | `/files`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(materials)'}/add-materials` | `/add-materials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}/create-report` | `/create-report`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}/report-detail` | `/report-detail`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/comments` | `/comments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/detail` | `/detail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/edit` | `/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/files` | `/files`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(materials)'}/add-materials` | `/add-materials`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}/create-report` | `/create-report`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}/report-detail` | `/report-detail`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(1tasks)'}/comments${`?${string}` | `#${string}` | ''}` | `/comments${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(1tasks)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(1tasks)'}/detail${`?${string}` | `#${string}` | ''}` | `/detail${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(1tasks)'}/edit${`?${string}` | `#${string}` | ''}` | `/edit${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(1tasks)'}/files${`?${string}` | `#${string}` | ''}` | `/files${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(1tasks)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(materials)'}/add-materials${`?${string}` | `#${string}` | ''}` | `/add-materials${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(reports)'}/create-report${`?${string}` | `#${string}` | ''}` | `/create-report${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(reports)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(reports)'}/report-detail${`?${string}` | `#${string}` | ''}` | `/report-detail${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/comments` | `/comments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/detail` | `/detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/edit` | `/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}/files` | `/files`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(1tasks)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(materials)'}/add-materials` | `/add-materials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}/create-report` | `/create-report`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(reports)'}/report-detail` | `/report-detail`; params?: Router.UnknownInputParams; };
    }
  }
}
